### PR TITLE
Fixing governance cd

### LINKED ISSUE #951: Improve the continuous deployment of code proposals
Epic: #154

### PR DESCRIPTION
**Pull request by tenmoves**
# Description

fix governance CD pipeline

Fixes #951 #974 #998 #970 #971

for testing  add the following to .iex.exs 
```
alias Archethic.Governance.Code.CICD.Docker
prop = %Archethic.Governance.Code.Proposal{
  address: <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221,
    177, 45, 120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118,
    170, 122, 142>>,
  previous_public_key: <<0, 1, 62, 205, 23, 142, 29, 217, 94, 202, 136, 109,
    165, 135, 153, 205, 202, 132, 122, 116, 97, 18, 90, 34, 141, 225, 172, 138,
    16, 138, 85, 15, 41, 149>>,
  timestamp: nil,
  description: "\Testing code proposal\"",
  changes: "diff --git a/mix.exs b/mix.exs\nindex a82c0b3c..b94d4323 100644\n--- a/mix.exs\n+++ b/mix.exs\n@@ -4,7 +4,7 @@ defmodule Archethic.MixProject do\n   def project do\n     [\n       app: :archethic,\n-      version: \"1.0.8-rc1\",\n+      version: \"1.0.9\",\n       build_path: \"_build\",\n       config_path: \"config/config.exs\",\n       deps_path: \"deps\",\ndiff --git a/rel/appups/archethic/1.0.8-rc1_to_1.0.9.appup b/rel/appups/archethic/1.0.8-rc1_to_1.0.9.appup\nnew file mode 100644\nindex 00000000..18b6d541\n--- /dev/null\n+++ b/rel/appups/archethic/1.0.8-rc1_to_1.0.9.appup\n@@ -0,0 +1,4 @@\n+{\"1.0.9\",\n+ [{\"1.0.8-rc1\",\n+   [{load_module,'Elixir.Archethic', []}]}],\n+ [{\"1.0.8-rc1\",\n+   [{load_module,'Elixir.Archethic', []}]}]\n+}.\n",
  version: "1.0.9",
  files: ["mix.exs", "rel/appups/archethic/1.0.8-rc1_to_1.0.9.appup"],
  approvals: [
    <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221, 177, 45,
      120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118, 170,
      122, 142>>,
    <<0, 0, 168, 220, 209, 92, 167, 255, 187, 168, 176, 63, 128, 210, 199, 35,
      63, 0, 252, 36, 147, 196, 130, 249, 233, 17, 132, 0, 6, 88, 232, 198, 98,
      44>>
  ]
}
```

and launch Docker.run_ci!(prop) and Docker.run_testnet!(prop).

### CODE REVIEW

**Comment by tenmoves** [comment]
in order to test add this to your .iex.exs file 
`alias Archethic.Governance.Code.CICD.Docker
prop = %Archethic.Governance.Code.Proposal{
  address: <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221,
    177, 45, 120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118,
    170, 122, 142>>,
  previous_public_key: <<0, 1, 62, 205, 23, 142, 29, 217, 94, 202, 136, 109,
    165, 135, 153, 205, 202, 132, 122, 116, 97, 18, 90, 34, 141, 225, 172, 138,
    16, 138, 85, 15, 41, 149>>,
  timestamp: nil,
  description: "\Testing code proposal\"",
  changes: "diff --git a/mix.exs b/mix.exs\nindex a82c0b3c..b94d4323 100644\n--- a/mix.exs\n+++ b/mix.exs\n@@ -4,7 +4,7 @@ defmodule Archethic.MixProject do\n   def project do\n     [\n       app: :archethic,\n-      version: \"1.0.7\",\n+      version: \"1.0.8\",\n       build_path: \"_build\",\n       config_path: \"config/config.exs\",\n       deps_path: \"deps\",\ndiff --git a/rel/appups/archethic/1.0.7_to_1.0.8.appup b/rel/appups/archethic/1.0.7_to_1.0.8.appup\nnew file mode 100644\nindex 00000000..18b6d541\n--- /dev/null\n+++ b/rel/appups/archethic/1.0.7_to_1.0.8.appup\n@@ -0,0 +1,4 @@\n+{\"1.0.8\",\n+ [{\"1.0.7\",\n+   [{load_module,'Elixir.Archethic', []}]}],\n+ [{\"1.0.7\",\n+   [{load_module,'Elixir.Archethic', []}]}]\n+}.\n",
  version: "1.0.8",
  files: ["mix.exs", "rel/appups/archethic/1.0.7_to_1.0.8.appup"],
  approvals: [
    <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221, 177, 45,
      120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118, 170,
      122, 142>>,
    <<0, 0, 168, 220, 209, 92, 167, 255, 187, 168, 176, 63, 128, 210, 199, 35,
      63, 0, 252, 36, 147, 196, 130, 249, 233, 17, 132, 0, 6, 88, 232, 198, 98,
      44>>
  ]
}`

then you can launch 
`Docker.run_ci!(prop)`

and after 
`Docker.run_testnet!(prop)`

File: config/config.exs [hunk 1]
```diff
@@ -12,9 +12,9 @@ config :git_hooks,
         {:cmd, "mix credo"},
         {:cmd, "mix sobelow"},
         {:cmd, "mix knigge.verify"},
-        {:cmd, "mix test --trace"},
-        {:cmd, "mix dialyzer"},
-        {:cmd, "mix check.updates"}
+        # {:cmd, "mix test --trace"},
```
Comment (samuelmanzanera) [inline config/config.exs:15]: I think this should be uncommented

File: lib/archethic/crypto.ex [hunk 2]
```diff
@@ -1141,22 +1141,26 @@ defmodule Archethic.Crypto do
...
-          nil ->
-            "no_key"
-
-          public_key ->
-            public_key
-        end
+    if System.get_env("ARCHETHIC_NETWORK_TYPE") == "testnet" do
+      ""
+    else
+      case Keyword.get(@certification_public_keys, ID.to_origin(origin_id)) do
```
Comment (samuelmanzanera) [inline lib/archethic/crypto.ex:1147]: Ideally it should be on the conf by replacing this existing conf with the check on the network's type
```elixir
config :archethic, Archethic.Crypto,
  root_ca_public_keys: [
    software: case System.get_env("ARCHETHIC_NETWORK_TYPE") do
      "testnet" -> []
       _ ->
         [
           secp256r1: ...
         ]
    end
...
    ]
  ]
```

So the check could remain constant and without direct access to the system environment variable from the code.

File: lib/archethic/db/embedded_impl/chain_index.ex [hunk 3]
```diff
@@ -40,7 +40,7 @@ defmodule Archethic.DB.EmbeddedImpl.ChainIndex do
     {:ok, %{db_path: db_path}}
   end
 
-  def code_change("1.0.7", state, _extra) do
+  def code_change("1.0.6", state, _extra) do
```
Comment (samuelmanzanera) [inline lib/archethic/db/embedded_impl/chain_index.ex:43]: It should be 1.0.7 I think

File: lib/archethic/governance/code/cicd/docker/cicd.ex [hunk 4]
```diff
@@ -193,36 +181,66 @@ defmodule Archethic.Governance.Code.CICD.Docker do
...
-    nodes = 1..nb_nodes |> Enum.map(&"#{compose_prefix}_node#{&1}_1")
+    validator_container = "#{compose_prefix}-validator-1"
+
+    nodes = 1..nb_nodes |> Enum.map(&"#{compose_prefix}-node#{&1}-1")
 
     with :ok <- Logger.info("#{dir} Prepare", address: address_encoded),
          :ok <- testnet_prepare(dir, address, version),
          :ok <- Logger.info("#{dir} Start", address: address_encoded),
-         {_, 0} <- testnet_start(dir, nb_nodes),
+         %{cmd: {_, 0}, testnet: _testnet} <- testnet_start(dir, nb_nodes),
```
Comment (samuelmanzanera) [inline lib/archethic/governance/code/cicd/docker/cicd.ex:196]: why do you need `testnet` variable as output ?

File: lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex [hunk 5]
```diff
@@ -3,11 +3,13 @@ defmodule Archethic.Networking.IPLookup.NATDiscovery.MiniUPNP do
 
   require Logger
 
-  @upnpc Application.app_dir(:archethic, "priv/c_dist/upnpc")
+  def upnpc() do
```
Comment (samuelmanzanera) [inline lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:6]: Why do you need to make it as function ?

File: lib/mix/tasks/validate.ex [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+           ]
+         ) do
+      {_, []} ->
+        Mix.shell().cmd("mix help #{Mix.Task.task_name(__MODULE__)}")
+
+      {parsed, nodes} ->
+        if parsed[:help] do
+          Mix.shell().cmd("mix help #{Mix.Task.task_name(__MODULE__)}")
+        else
+          :ok = maybe(parsed, :phase, &Validator.run/2, [nodes, parsed[:phase]])
```
Comment (samuelmanzanera) [inline lib/mix/tasks/validate.ex:40]: maybe you don't need the 3rd parameter in the `maybe/4` 

also it seems some redundancy between opts[key] and parsed[:phase]

File: lib/archethic/governance/code/cicd/docker/cicd.ex (hunk 4 above)
Comment (tenmoves) [reply lib/archethic/governance/code/cicd/docker/cicd.ex:196]: I was doing some tests for multi stage validation, this will be needed for sure that's why I left it there.

File: lib/archethic/db/embedded_impl/chain_index.ex (hunk 3 above)
Comment (tenmoves) [reply lib/archethic/db/embedded_impl/chain_index.ex:43]: no with 1.0.7 it will not work @Neylix experienced the same issue when doing manual upgrade in testnet

File: lib/archethic/crypto.ex (hunk 2 above)
Comment (tenmoves) [reply lib/archethic/crypto.ex:1147]: ok

File: config/config.exs (hunk 1 above)
Comment (tenmoves) [reply config/config.exs:15]: yes, but there is an issue with this I created a separate ticket for that however it needs to be uncommented to not affect hooks usage in other areas than governance for now

File: lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex (hunk 5 above)
Comment (tenmoves) [reply lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:6]: because the path change between compile time and run time as we cp the resulting tar gz from ci container to cd containers.

Comment (samuelmanzanera) [reply lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:6]: Is the UPnP still called/needed on the docker releases ?

File: lib/archethic/governance/code/cicd/docker/cicd.ex (hunk 4 above)
Comment (samuelmanzanera) [reply lib/archethic/governance/code/cicd/docker/cicd.ex:196]: ok

File: lib/mix/tasks/validate.ex (hunk 6 above)
Comment (samuelmanzanera) [reply lib/mix/tasks/validate.ex]: ok

File: lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex (hunk 5 above)
Comment (tenmoves) [reply lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:6]: normally no, but I did this for other binaries as well, should I make revert the change on upnpc while keeping the change on the others ?

Comment (samuelmanzanera) [reply lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:6]: no harm, maybe make the function private

File: lib/mix/tasks/utils.ex [hunk 7]
```diff
@@ -0,0 +1,11 @@
+defmodule Mix.Tasks.Utils do
+  @moduledoc false
+
+  def maybe(opts, key, func, args) do
```
[the remark this answers is not in the document]
Comment (tenmoves) [reply lib/mix/tasks/utils.ex]: done

File: lib/archethic/db/embedded_impl/chain_index.ex (hunk 3 above)
Comment (samuelmanzanera) [reply lib/archethic/db/embedded_impl/chain_index.ex:43]: I don't get it because the latest version deployed in the 1.0.7 and the chain index's cache off loading isn't deployed yet.

Comment (samuelmanzanera) [reply lib/archethic/db/embedded_impl/chain_index.ex:43]: I've seen with @Neylix, I think you can let it as before, it was just for the tests. :)

Comment (tenmoves) [reply lib/archethic/db/embedded_impl/chain_index.ex]: ok done

File: config/config.exs (hunk 1 above)
Comment (tenmoves) [reply config/config.exs]: done

**Review by bchamagne — APPROVED** [review]

**Comment by bchamagne** [comment]
Updated proposal for 1.1.0-rc2 to 1.1.0-rc3
```
alias Archethic.Governance.Code.CICD.Docker
prop = %Archethic.Governance.Code.Proposal{
  address: <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221,
    177, 45, 120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118,
    170, 122, 142>>,
  previous_public_key: <<0, 1, 62, 205, 23, 142, 29, 217, 94, 202, 136, 109,
    165, 135, 153, 205, 202, 132, 122, 116, 97, 18, 90, 34, 141, 225, 172, 138,
    16, 138, 85, 15, 41, 149>>,
  timestamp: nil,
  description: "\Testing code proposal\"",
  changes: "diff --git a/mix.exs b/mix.exs\nindex a82c0b3c..b94d4323 100644\n--- a/mix.exs\n+++ b/mix.exs\n@@ -4,7 +4,7 @@ defmodule Archethic.MixProject do\n   def project do\n     [\n       app: :archethic,\n-      version: \"1.1.0-rc2\",\n+      version: \"1.1.0-rc3\",\n       build_path: \"_build\",\n       config_path: \"config/config.exs\",\n       deps_path: \"deps\",\ndiff --git a/rel/appups/archethic/1.1.0-rc2_to_1.1.0-rc3.appup b/rel/appups/archethic/1.1.0-rc2_to_1.1.0-rc3.appup\nnew file mode 100644\nindex 00000000..18b6d541\n--- /dev/null\n+++ b/rel/appups/archethic/1.1.0-rc2_to_1.1.0-rc3.appup\n@@ -0,0 +1,4 @@\n+{\"1.1.0-rc3\",\n+ [{\"1.1.0-rc2\",\n+   [{load_module,'Elixir.Archethic', []}]}],\n+ [{\"1.1.0-rc2\",\n+   [{load_module,'Elixir.Archethic', []}]}]\n+}.\n",
  version: "1.1.0-rc3",
  files: ["mix.exs", "rel/appups/archethic/1.1.0-rc2_to_1.1.0-rc3.appup"],
  approvals: [
    <<0, 0, 135, 189, 175, 8, 43, 160, 49, 21, 23, 241, 61, 189, 221, 177, 45,
      120, 59, 243, 80, 75, 193, 250, 119, 188, 219, 73, 209, 197, 118, 170,
      122, 142>>,
    <<0, 0, 168, 220, 209, 92, 167, 255, 187, 168, 176, 63, 128, 210, 199, 35,
      63, 0, 252, 36, 147, 196, 130, 249, 233, 17, 132, 0, 6, 88, 232, 198, 98,
      44>>
  ]
}
Docker.run_ci!(prop)
Docker.run_testnet!(prop)
```
