### PR TITLE
Change transaction value fee to a fixed one (base fee)

### LINKED ISSUE #349: Change transaction fee with base fee
We should adapt the transaction fee algorithm to use a base fee (flat tax) to avoid transaction's value fee .
This causing unfair fee calculation and not efficient with non financial transaction.

A first assumption should be 0.1 UCO fee (~1ct) (via OracleChain from the USD/EUR price)

### PR DESCRIPTION
**Pull request by blackode**
# Description
The transaction fee value for oracle transactions have been set with `0.01/uco_price_in_usd` 

Fixes #349 

## Type of change
- New feature (non-breaking change which adds functionality)

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/archethic/mining/fee.ex [hunk 1]
```diff
@@ -42,11 +42,8 @@ defmodule Archethic.Mining.Fee do
       true == Transaction.network_type?(type) ->
         0
 
-      type == :oracle ->
-        0.01 / uco_price_in_usd
-
       true ->
-        transaction_value = get_transaction_value(tx) / @unit_uco
+        transaction_value = 0.01 / uco_price_in_usd
```
Comment (samuel-uniris) [inline lib/archethic/mining/fee.ex:46]: I think you should make the change here:

https://github.com/archethic-foundation/archethic-node/blob/3c24793b3c00085b5f3ccfabafe8ca557a604e99/lib/archethic/mining/fee.ex#L99

As there is no more transaction value fee

File: lib/archethic/mining/fee.ex [hunk 2]
```diff
@@ -95,14 +86,13 @@ defmodule Archethic.Mining.Fee do
...
          uco_price_in_usd,
-         transaction_value,
          nb_bytes,
          nb_storage_nodes,
          nb_recipients
        ) do
     # TODO: determine the fee for smart contract execution
 
-    value_cost = fee_for_value(uco_price_in_usd, transaction_value)
+    value_cost = 0.01 / uco_price_in_usd
```
Comment (samuel-uniris) [inline lib/archethic/mining/fee.ex:95]: I think you can rename it as "minimum fee"
You could also use a constant for the 0.01 , this will be easier to update.

File: test/archethic/mining/fee_test.exs [hunk 3]
```diff
@@ -20,7 +20,7 @@ defmodule Archethic.Mining.FeeTest do
 
     test "should return a fee less than amount to send for a single transfer" do
       # 0.050048 UCO for 1 UCO at $0.2
-      assert 50_048_000 =
```
Comment (samuel-uniris) [inline test/archethic/mining/fee_test.exs:23]: Can you also change the comments values

Comment (blackode) [reply test/archethic/mining/fee_test.exs:23]: I have updated all fee comments with new value by dividing with `100000000`

**Review by samuel-uniris — APPROVED** [review]
