### PR TITLE
Fix GeoPatch algorithm

### LINKED ISSUE #253: Fix GeoPatch algorithm
This is an issue in the current algorithm raised in the #238
There is a problem with the last digit of the geo patch as it's not match the geo coordinates.

Solution:
Rebuild the Geo-Patch ID Algo Entirely: (takes only 5-10 lines of code)

Geolocation patch for a node is represented by 3 Digits, for example “XYZ”  where 
First Digit (X) is the longitude patch id
Second Digit (Y)  is the latitude patch id
Third Digit (Z) is for better precision within the patch
First Digit and Second Digits give the patch ID, the third digit gives more precision

For example on the graph where a node is represented by C68, where 
C is the longitude patch id
6 is the latitude patch id
8 is the node’s precision within the C6 Patch
Digits can vary from [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F]

- [x] Step 1: (longitude, latitude) 
Obtain the Geolocation represented in terms of longitude (-180,180), latitude (-90,90).
Eg 1: Node A = (82, 36) (82 is longitude and 36 is latitude)
Eg 2: Node B = (-82, 36) (-82 is longitude and 36 is latitude)
Eg 3: Node C = (82, -36) (82 is longitude and -36 is latitude)
Eg 4: Node D = (-82, -36) (-82 is longitude and -36 is latitude)

- [x] Step 2: (longitude_reference, latitude_reference)
(longitude_reference, latitude_reference) = (longitude / 22.5, latitude / 22.5)
Eg 1: (longitude_reference, latitude_reference) of Node A(82, 36) = (3.64, 1.6)
Eg 2: (longitude_reference, latitude_reference) of Node A(-82, 36) = (-3.64, 1.6)
Eg 3: (longitude_reference, latitude_reference) of Node A(82, -36) = (3.64, -1.6)
Eg 4: (longitude_reference, latitude_reference) of Node A(-82, -36) = (-3.64, -1.6)

- [x] Step 3: (First Digit, Second Digit)
First Digit & Second Digit =  [8,  9,  A,  B,  C, D,  E,  F,  0, 1, 2, 3, 4, 5, 6, 7, 8]
Graphical Value in Range = [-8,-7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]
Assign the first digit and second digit based on the graphical range

- [x] Step 4: (longitude_second_reference, latitude_second_reference) 
Calculate the Third Digit for better precision
(longitude_second_reference, latitude_second_reference) = decimal portion of (longitude_reference, latitude_reference)
If decimal portion of (longitude_reference, latitude_reference) is negative subtract 1 by that number
Eg 1: Node A = (82, 36) (82 is longitude and 36 is latitude)
(longitude_reference, latitude_reference) of Node A = (3.64, 1.6)
(longitude_second_reference, latitude_second_reference) of Node A = (0.64,0.6)
Eg 2: Node B = (-82, -36) (-82 is longitude and -36 is latitude)
(longitude_reference, latitude_reference) of Node B = (-3.64, -1.6)
(longitude_second_reference, latitude_second_reference) of Node A = (0.36,0.4)

Based on the decimal value range, add the third digit

### PR DESCRIPTION
**Pull request by Neylix**
# Description

Fixes bug on GeoPatch algorithm to match the following rules : 
- first digit represent latitude patch
- second digit represent longitude patch
- third digit is a precision within the previous two digits

Fixes #253 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Runned a script with all coordinates possibilities (2 nested loop from -90 to 90 and -180 to 180), result is 2048 distinct geo patch (16x8x16)
- Geo patch match the grid coordinates shown in issue (pos 0,0 is patch 000, pos -1,-1 is patch FFF)

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Neylix** [comment]
Requested review form @samuel-uniris @I-Archer-Zero

**Review by imnik11 — COMMENTED** [review]
Overall looks good and precision is improved

File: lib/archethic/p2p/geo_patch.ex [hunk 1]
```diff
@@ -29,68 +29,34 @@ defmodule ArchEthic.P2P.GeoPatch do
   end
 
   defp compute_patch(lat, lon) do
-    lat_sign = sign(lat)
-    lon_sign = sign(lon)
+    lat_pos = (lat + 90) / 11.25
+    lon_pos = (lon + 180) / 22.5
```
Comment (imnik11) [inline lib/archethic/p2p/geo_patch.ex:33]: @I-Archer-Zero 
Looks like added 90,180 to avoid negative sign but look at 

`
lat_pos 
`

Comment (imnik11) [reply lib/archethic/p2p/geo_patch.ex:33]: It must be
`lat_pos = (lat + 90) / 22.5`

Comment (Neylix) [reply lib/archethic/p2p/geo_patch.ex:33]: Hi !
Dividing lat by 22.5 will have a result between 0 and 8. But we are looking for a range between 0 and 16 to get all hexadecimal possibilities (0 to F).
Si we have to divide by 11.25 to get it.

I think on issue's example there is a mismatch. On the graph, latitude only have 8 parts, but on explication bellow it says that first 2 digits are on range of 0 to F so 16 parts...

Comment (samuel-uniris) [reply lib/archethic/p2p/geo_patch.ex:33]: @I-Archer-Zero

Comment (I-Archer-Zero) [reply lib/archethic/p2p/geo_patch.ex:33]: Hi @Neylix 
Good observation 

lat should be divided by 22.5 and not 11.25 because we need square patches (not rectangle)
This also means that the lat/22.5 will have a result between 0 to 8

**Review by imnik11 — COMMENTED** [review]
@Neylix @internet-zero

The Edge case problem is till in the new Algo but I avoided it by taking that also in the range 
so, earlier 
` defp index_patch([f_i, s_i]) when f_i > 0.5 and f_i <= 1 and s_i < -0.5 and s_i >= -1, do: '0'`

and when we input (-45, x) it crashed and it shall be avoided 
by using just `>=` while condition check

Now
`  defp precision_patch(lat, lon) when lat >= 0 and lat <= 0.25 and lon >= 0 and lon <= 0.25, do: '0'`

File: lib/archethic/p2p/geo_patch.ex (hunk 1 above)
Comment (Neylix) [reply lib/archethic/p2p/geo_patch.ex:33]: Hi ! Thanks for your return.
I didn't know it had to be a square, I'll update it as you requested. Also need to add 4 to result to get index from C to 3 as in your graph.
I also noticed that in issue you say that first digit is for longitude index, but I did latitude first, should I update it too ?
I'm actually out of my PC until sunday, I'll update it at this time.

Comment (Neylix) [reply lib/archethic/p2p/geo_patch.ex:36]: Hello ! 
I fixed calculation in lastest commits

**Comment by Neylix** [comment]
@imnik11 
Hello ! I did some tests with the values -45,x but it seems to work, I added these in test files and it going well.
Can you show the error you got ?

File: lib/archethic/p2p/geo_patch.ex [hunk 2]
```diff
@@ -24,73 +24,44 @@ defmodule ArchEthic.P2P.GeoPatch do
...
-    lon_sign = sign(lon)
-
-    fdc = [lat / 90, lon / 180]
-
-    sd =
-      [(lat - lat_sign * 45) / 2, (lon - lon_sign * 90) / 2]
-      |> resolve_with_sign([lat, lon])
+    lon_pos = (lon + 180) / 22.5
+    # Adding 4 to have second digit hex value from C to 3
+    lat_pos = (lat + 90) / 22.5 + 4
```
Comment (imnik11) [inline lib/archethic/p2p/geo_patch.ex:38]: avoid adding 4 and adding 90, 180 was in earlier implementation so, avoid it

Comment (Neylix) [reply lib/archethic/p2p/geo_patch.ex:42]: Hello ! 
I don't really understand your suggestion. Here is why I choose this implementation instead of the one did before : 
The first calculations with adding 90 / 180 / 4 result in an index between 0 and 15 for ```lon_pos``` one and between 4 and 11 for ```lat_pos```.
With these index, we can easily find the good hexadecimal value in the array of the function ```main_index_patch```.

The advantage of this implementation is that it takes less ressources and less execution times than the previous implementation, i.e guetting a value from an array by his index is faster than doing multiple if condition to find the good hexadecimal value.
An other advantage is that it takes less lines of code.

To be easier to read, instead of adding 4 to ```lat_pos``` we can create a new array [C,D,E,F,0,1,2,3] and get hexadecimal value from it, but I think that using same array as for ```lon_pos``` is better to reduce memory usage.

@samuel-uniris What is your advice about it ?

Comment (samuel-uniris) [reply lib/archethic/p2p/geo_patch.ex:42]: So in term of performance pattern matching (multiple function clause) is like if/else block under the good bu is quite fast and optimized during compilation.

Accessing a random element in a list is not the same in Erlang. List are not arrays but linked list , which means to access nth element, need to scan nth before . When the list is big is not efficient. 
However if the list is bounded, know and static, you can leverage tuple where access a specific element is fast. 

There is different strategy for this problem. 

In term of readability the pattern matching is better when you have a several if/else/case blocks.

Comment (samuel-uniris) [reply lib/archethic/p2p/geo_patch.ex:42]: So in term of performance pattern matching (multiple function clause) is like if/else block under the good bu is quite fast and optimized during compilation.

Accessing a random element in a list is not the same in Erlang. List are not arrays but linked list , which means to access nth element, need to scan nth before . When the list is big is not efficient. 
However if the list is bounded, know and static, you can leverage tuple where access a specific element is fast. 

There is different strategy for this problem. 

In term of readability the pattern matching is better when you have a several if/else/case blocks.

Comment (Neylix) [reply lib/archethic/p2p/geo_patch.ex:42]: Hi ! Updated in last commit to use tuple. Using pattern matching function was not as easy to read because it needs to much function to catch all conditions.

**Comment by samuel-uniris** [comment]
Seems more clear now.
Could you add more tests to be sure close locations, would be closed about the geo-patch, for instance in the 1st and 2nd digit but maybe not the 3rd

**Comment by Neylix** [comment]
Added some tests with near location cities

File: test/archethic/p2p/geo_patch_test.exs [hunk 3]
```diff
@@ -40,5 +56,9 @@ defmodule ArchEthic.P2P.GeoPatchTest do
     assert "A1A" == GeoPatch.from_ip({15, 62, 246, 57})
     assert "021" == GeoPatch.from_ip({109, 164, 214, 168})
     assert "8C0" == GeoPatch.from_ip({1, 2, 3, 4})
+    assert "F1F" == GeoPatch.from_ip({1, 1, 1, 1})
```
Comment (samuel-uniris) [inline test/archethic/p2p/geo_patch_test.exs:59]: Is this distance good ? I mean it's almost close

Comment (Neylix) [reply test/archethic/p2p/geo_patch_test.exs:59]: Yes, first digit F means that longitude is >= -22.5 and < 0, when going in positive we return to 0. i.e 0 is >= 0 and < 22.5.
So just after FFF we have 000.

Comment (samuel-uniris) [reply test/archethic/p2p/geo_patch_test.exs:59]: Ok .
@imnik11 can you have a last check ?
