### PR TITLE
Correct self repair notifier

### LINKED ISSUE #348: Fix self repair notifier
A notifier is implemented when the topology changes triggering the a self repair because the shards change

However the process is crashing causing errors from the DB mentioning the transactions don't exist.

This should be fixed to reactive it (being disabled) and support this shard repairing.

### PR DESCRIPTION
**Pull request by samuel-uniris**
Trigger repair on the right P2P network change

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #348 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

When an authorized node is considered as unauthorized or globally offline, this means a topology change occurred, hence the notifier will repair transaction shards but proposing transactions to new storage nodes.

By disconnecting an authorized node the notifier should replicate all the transactions this node was in charge of.
Logs are also added to help to visualize the events.

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/archethic/self_repair/notifier.ex [hunk 1]
```diff
@@ -1,104 +1,172 @@
...
+  require Logger
 
   def start_link(args \\ []) do
     GenServer.start_link(__MODULE__, args)
   end
 
   def init(_) do
     PubSub.register_to_node_update()
-    {:ok, []}
+    {:ok, %{notified: %{}}}
```
Comment (apoorv-2204) [inline lib/archethic/self_repair/notifier.ex:50]: if there is process crash??, and in a situation where all nodes  waiting for each other for node_update:  message?

Comment (samuel-uniris) [reply lib/archethic/self_repair/notifier.ex:50]: This state is just to avoid multiple node_update message for a given node, to avoid multiple repair in a close time.

Comment (samuel-uniris) [reply lib/archethic/self_repair/notifier.ex:50]: If the process crashes, it will restart with an empty state, and wait another message of unavailability of the node

**Review by prix-uniris — APPROVED** [review]
LGTM
