### PR TITLE
ensure code proposal contains a valid appup file with the right versions

### LINKED ISSUE #873: Ensure each code proposal includes appup
In the current version, code proposals are built from text/plain style:
```
Description: ......
Changes:
{git diff}
```

However, to be complete and to avoid unexpected results during the upgrade, we should require the appup instructions to be present.
Hence, we could check the impact of the code proposals and the proposal's correctness.

### PR DESCRIPTION
**Pull request by tenmoves**
# Description

In the current version, code proposals are built from text/plain style:

Description: ......
Changes:
{git diff}
However, to be complete and to avoid unexpected results during the upgrade, we should require the appup instructions to be present.
Hence, we could check the impact of the code proposals and the proposal's correctness.

Fixes #873

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- Unit tests

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/archethic/governance/code.ex [hunk 1]
```diff
@@ -77,6 +80,58 @@ defmodule Archethic.Governance.Code do
...
+           |> Distillery.Releases.Appup.Utils.validate_instructions() do
+      true
+    else
+      _ -> false
+    end
+  end
+
+  # working around a bug in typespecs for :erl_eval.eval_str
+  @spec eval_str(binary()) :: any
+  def eval_str(str) do
```
Comment (samuelmanzanera) [inline lib/archethic/governance/code.ex:123]: Maybe private

File: test/archethic/governance/code_test.exs [hunk 2]
```diff
@@ -30,5 +30,45 @@ defmodule Archethic.Governance.CodeTest do
...
+
+    current_version = "1.0.7"
+    version = "1.0.8"
+
+    assert Code.valid_appup?(changes, version, current_version)
+  end
+
+  test "valid_appup? should fail because appup contains illegal instruction" do
+    changes =
+      "diff --git a/mix.exs b/mix.exs\nindex c615ed94..d16e2d6f 100644\n--- a/mix.exs\n+++ b/mix.exs\n@@ -4,7 +4,7 @@ defmodule Archethic.MixProject do\n   def project do\n     [\n       app: :archethic,\n-      version: \"1.0.7\",\n+      version: \"1.0.8\",\n       build_path: \"_build\",\n       config_path: \"config/config.exs\",\n       deps_path: \"deps\",\ndiff --git a/rel/appups/archethic/1.0.7_to_1.0.8.appup b/rel/appups/archethic/1.0.7_to_1.0.8.appup\nnew file mode 100644\nindex 00000000..0f18b8e1\n--- /dev/null\n+++ b/rel/appups/archethic/1.0.7_to_1.0.8.appup\n@@ -0,0 +1,4 @@\n+{\"1.0.8\",\n+ [{\"1.0.7\",\n+   [{load_module_toto,'TOTO', []}]}]\n+}.\n\\ No newline at end of file"
```
Comment (samuelmanzanera) [inline test/archethic/governance/code_test.exs:45]: Can you do multiple lines here ?

**Review by samuelmanzanera — COMMENTED** [review]
Thanks for the PR.
Seems great 👍

I put some remarks, I would have to test it in the meantime.

File: test/archethic/governance/code_test.exs (hunk 2 above)
Comment (samuelmanzanera) [reply test/archethic/governance/code_test.exs:45]: ok

Comment (samuelmanzanera) [reply test/archethic/governance/code_test.exs:45]: It can be a way or using IO lists

**Review by samuelmanzanera — APPROVED** [review]
