### PR TITLE
Fix authorized nodes unavailability

### LINKED ISSUE #318: Temporary unavailability of miners cause proof of election failure
### What happened?

An error is raised when a previous authorized node become unavailable and the node shared secrets's renewal is performed, excluding this node from the list.

Then, when the node comes back, it's considered as authorized nodes but without the knowledge of previous daily nonce, causing an error of proof of election verification.

### What is expected ?

An authorized node should be able to rejoin the network without causing issue in the transaction validation

### PR DESCRIPTION
**Pull request by samuel-uniris**
# Description

This PR aims to resolve issue regarding nodes which become unavailable and try to rejoin later while the node shared secrets have been performed since.

But once the node is coming back it should be able to load missed transactions without issue regarding election or shared secrets

Fixes #318 

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Start few nodes and wait they become authorized
- Stop one
- Wait this node becomes unavailable
- Wait other nodes perform shared secrets transactions
- Start the paused node
- It should be able to decode the missed transactions and start validate transaction again

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: lib/archethic/shared_secrets/node_renewal.ex [hunk 1]
```diff
@@ -50,10 +50,19 @@ defmodule Archethic.SharedSecrets.NodeRenewal do
   @spec next_authorized_node_public_keys() :: list(Crypto.key())
   def next_authorized_node_public_keys do
     DB.get_latest_tps()
-    |> Election.next_authorized_nodes(P2P.available_nodes())
+    |> Election.next_authorized_nodes(candidates(), P2P.authorized_nodes())
     |> Enum.map(& &1.last_public_key)
```
Comment (Neylix) [inline lib/archethic/shared_secrets/node_renewal.ex:54]: It should be `first_public_key` because if node disconnect and reconnect, it will have a new last public key but during disconnection time, other nodes don't know the new public key of the node.
And so when the node reconnect it will not be able to descrypt the secret as it's last public key is not the same than the one added by others nodes in the transaction.
By updating this, node shared secrets transaction have to be decrypted with node first public key

**Review by Neylix — CHANGES_REQUESTED** [review]

**Review by Neylix — APPROVED** [review]

**Comment by apoorv-2204** [comment]
@Neylix   I think We can test this on  3 node network.

**Comment by apoorv-2204** [comment]
Soo many changes and Soo many commits.

File: lib/archethic_web/templates/node/list.html.leex [hunk 2]
```diff
@@ -4,30 +4,56 @@
...
+      </div>
+      <%= for node <- @authorized_nodes do %>
+        <div class="box">
+          <div class="columns is-desktop">
+            <div class="column">
+                <div>
+                    <p class="heading">First public key</p>
+                    <%= link to: Routes.live_path(@socket, ArchethicWeb.NodeDetailsLive, Base.encode16(node.last_public_key)) do%>
+                      <span class="is-hidden-mobile"><%= Base.encode16(:binary.part(node.first_public_key, 0, 30)) %>...</span>
+                      <span class="is-hidden-touch"><%= Base.encode16(:binary.part(node.first_public_key, 0, 13)) %>...</span>
```
Comment (Neylix) [inline lib/archethic_web/templates/node/list.html.leex:24]: To be more responsive you should do something like this to avoid double line :
```html
<span class="is-hidden-tablet"><%= Base.encode16(:binary.part(node.first_public_key, 0, 10)) %>...</span>
```

**Review by Neylix — CHANGES_REQUESTED** [review]

**Review by Neylix — APPROVED** [review]

File: lib/archethic_web/templates/node/list.html.leex (hunk 2 above)
Comment (samuel-uniris) [reply lib/archethic_web/templates/node/list.html.leex]: done

**Comment by apoorv-2204** [comment]
Wait its done???  so fast?
